/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import Clases.CondicionMigratoria;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSNotifyFade;

/**
 *
 * @author Family
 */
public class panelParametroCondicionMigratoria extends javax.swing.JPanel {

    ArrayList<CondicionMigratoria> condiciones = new ArrayList();
    int valor = -1;
    String estado = "Activo";
    public boolean agregar=true;
    public boolean editar=true;
    public panelParametroCondicionMigratoria() {
        initComponents();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new rojerusan.RSTableMetro();
        buttonPane1 = new rojeru_san.complementos.ButtonPane();
        guardarBtn = new RSComponentShade.RSButtonRippleShade();
        bloqueadoRb = new rojerusan.RSRadioButton();
        activoRb = new rojerusan.RSRadioButton();
        jLabel3 = new javax.swing.JLabel();
        idTxt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreTxt = new rojeru_san.rsfield.RSTextFullRound();
        nuevoBtn = new RSComponentShade.RSButtonRippleShade();
        editarBtn = new RSComponentShade.RSButtonRippleShade();
        resetBtn = new RSComponentShade.RSButtonRippleShade();

        setBackground(new java.awt.Color(230, 230, 230));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_ios_photos_30px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Administración de Condición Migratoria");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Valor", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setBackgoundHead(new java.awt.Color(230, 230, 230));
        tabla.setColorBorderHead(new java.awt.Color(51, 51, 51));
        tabla.setColorBorderRows(new java.awt.Color(255, 255, 255));
        tabla.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tabla.setColorSecondary(new java.awt.Color(255, 255, 255));
        tabla.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tabla.setForegroundHead(new java.awt.Color(0, 0, 0));
        tabla.setGridColor(new java.awt.Color(0, 0, 0));
        tabla.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setMinWidth(80);
            tabla.getColumnModel().getColumn(0).setPreferredWidth(80);
            tabla.getColumnModel().getColumn(0).setMaxWidth(90);
            tabla.getColumnModel().getColumn(2).setMinWidth(120);
            tabla.getColumnModel().getColumn(2).setPreferredWidth(120);
            tabla.getColumnModel().getColumn(2).setMaxWidth(180);
        }

        buttonPane1.setBackground(new java.awt.Color(230, 230, 230));
        buttonPane1.setColorHover(new java.awt.Color(60, 60, 60));
        buttonPane1.setColorNormal(new java.awt.Color(59, 59, 59));
        buttonPane1.setOpaque(false);

        guardarBtn.setBackground(new java.awt.Color(230, 230, 230));
        guardarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_save_36px.png"))); // NOI18N
        guardarBtn.setToolTipText("Guardar");
        guardarBtn.setBgHover(new java.awt.Color(110, 110, 110));
        guardarBtn.setBgShade(new java.awt.Color(59, 59, 59));
        guardarBtn.setBgShadeHover(new java.awt.Color(59, 59, 59));
        guardarBtn.setEnabled(false);
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(bloqueadoRb);
        bloqueadoRb.setForeground(new java.awt.Color(0, 0, 0));
        bloqueadoRb.setText("Bloqueado");
        bloqueadoRb.setColorCheck(new java.awt.Color(0, 204, 255));
        bloqueadoRb.setColorUnCheck(new java.awt.Color(150, 150, 150));
        bloqueadoRb.setEnabled(false);
        bloqueadoRb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bloqueadoRbItemStateChanged(evt);
            }
        });
        bloqueadoRb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bloqueadoRbStateChanged(evt);
            }
        });

        buttonGroup1.add(activoRb);
        activoRb.setForeground(new java.awt.Color(0, 0, 0));
        activoRb.setSelected(true);
        activoRb.setText("Activo");
        activoRb.setColorCheck(new java.awt.Color(0, 204, 255));
        activoRb.setColorUnCheck(new java.awt.Color(150, 150, 150));
        activoRb.setEnabled(false);
        activoRb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                activoRbItemStateChanged(evt);
            }
        });
        activoRb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                activoRbStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ID:");

        idTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idTxt.setText("-");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Valor:");

        nombreTxt.setEditable(false);
        nombreTxt.setBackground(new java.awt.Color(230, 230, 230));
        nombreTxt.setForeground(new java.awt.Color(0, 0, 0));
        nombreTxt.setBorderColor(new java.awt.Color(51, 51, 51));
        nombreTxt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        nombreTxt.setPhColor(new java.awt.Color(255, 255, 255));
        nombreTxt.setPlaceholder("Ingrese el valor");
        nombreTxt.setSelectionColor(new java.awt.Color(0, 102, 102));
        nombreTxt.setSoloLetras(true);
        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });
        nombreTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreTxtKeyReleased(evt);
            }
        });

        nuevoBtn.setBackground(new java.awt.Color(230, 230, 230));
        nuevoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_add_32px.png"))); // NOI18N
        nuevoBtn.setToolTipText("Agregar Género");
        nuevoBtn.setBgHover(new java.awt.Color(110, 110, 110));
        nuevoBtn.setBgShade(new java.awt.Color(59, 59, 59));
        nuevoBtn.setBgShadeHover(new java.awt.Color(59, 59, 59));
        nuevoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBtnActionPerformed(evt);
            }
        });

        editarBtn.setBackground(new java.awt.Color(230, 230, 230));
        editarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_edit_32px_3.png"))); // NOI18N
        editarBtn.setToolTipText("Editar Género");
        editarBtn.setBgHover(new java.awt.Color(110, 110, 110));
        editarBtn.setBgShade(new java.awt.Color(59, 59, 59));
        editarBtn.setBgShadeHover(new java.awt.Color(59, 59, 59));
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(230, 230, 230));
        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_refresh_24px.png"))); // NOI18N
        resetBtn.setToolTipText("Actualizar Valores");
        resetBtn.setBgHover(new java.awt.Color(110, 110, 110));
        resetBtn.setBgShade(new java.awt.Color(59, 59, 59));
        resetBtn.setBgShadeHover(new java.awt.Color(59, 59, 59));
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPane1Layout = new javax.swing.GroupLayout(buttonPane1);
        buttonPane1.setLayout(buttonPane1Layout);
        buttonPane1Layout.setHorizontalGroup(
            buttonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPane1Layout.createSequentialGroup()
                .addGroup(buttonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(activoRb, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bloqueadoRb, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPane1Layout.createSequentialGroup()
                        .addGroup(buttonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(buttonPane1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(buttonPane1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuevoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        buttonPane1Layout.setVerticalGroup(
            buttonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPane1Layout.createSequentialGroup()
                .addGroup(buttonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(buttonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bloqueadoRb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(activoRb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(buttonPane1Layout.createSequentialGroup()
                .addComponent(nuevoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        new Thread(this::reset).start();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void nuevoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBtnActionPerformed
        nombreTxt.requestFocus();
        valor = 0;
        activarDesactivar(true);
        bloqueadoRb.setEnabled(false);
        activoRb.setSelected(true);
        editarBtn.setEnabled(false);
        nombreTxt.setText("");
        idTxt.setText("-");
        guardarBtn.setEnabled(true);
        nuevoBtn.setEnabled(false);
    }//GEN-LAST:event_nuevoBtnActionPerformed

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
        
        int fila = tabla.getSelectedRow();
        String id = fila >= 0 ? tabla.getValueAt(fila, 0).toString() : "-";
        if (fila >= 0 && !id.equals("-")) {
            activarDesactivar(true);
            valor = 1;
            editarBtn.setEnabled(false);
            int idint = Integer.valueOf(id);
            valor = 1;
            for (CondicionMigratoria condicion : condiciones) {
                if (idint == condicion.getId()) {
                    idTxt.setText(condicion.getId() + "");
                    nombreTxt.setText(condicion.getNombre());
                    if (condicion.getEstado().equalsIgnoreCase("activo")) {
                        activoRb.setSelected(true);
                    } else {
                        bloqueadoRb.setSelected(true);
                    }
                }
            }
            nuevoBtn.setEnabled(false);
            guardarBtn.setEnabled(true);
        } else {
            new rojerusan.RSNotifyFade("¡¡No hay Selección!! ", "Seleccione un valor en la tabla valido para editar!", 3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.INFORMATION).setVisible(true);

        }
    }//GEN-LAST:event_editarBtnActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int fila = tabla.getSelectedRow();
        String id = fila >= 0 ? tabla.getValueAt(fila, 0).toString() : "-";
        if (fila >= 0 && !id.equals("-") && valor < 0) {
            int idint = Integer.valueOf(id);
            for (CondicionMigratoria condicion : condiciones) {
                if (idint == condicion.getId()) {
                    idTxt.setText(condicion.getId() + "");
                    nombreTxt.setText(condicion.getNombre());
                    if (condicion.getEstado().equalsIgnoreCase("activo")) {
                        activoRb.setSelected(true);
                    } else {
                        bloqueadoRb.setSelected(true);
                    }
                }

            }
        } else {
            new rojerusan.RSNotifyFade("¡¡No hay Selección!! ", "Seleccione un valor en la tabla valido para editar!", 3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.INFORMATION).setVisible(true);

        }
    }//GEN-LAST:event_tablaMouseClicked

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        if (validarCamposLlenos() == true) {
            String nombre = nombreTxt.getText();

            if (valor == 0) {//nuevo
                boolean repetido = false;
                for (CondicionMigratoria condicion : condiciones) {
                    if (condicion.getNombre().equalsIgnoreCase(nombre)) {
                        repetido = true;
                    }
                }
                if (repetido == false) {
                    int respuesta = new CondicionMigratoria().newCondicion(nombre);
                    if (respuesta > 0) {
                        new rojerusan.RSNotifyFade("¡¡Agregado!! ", "Condición Migratoria agregado con exito!", 4, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                        limpiarCampos();
                        buscarValorTabla(nombre);
                        ParametrosPanel.actualizarPams("condicion");
                    } else {
                        new rojerusan.RSNotifyFade("¡¡ERROR!! ", "No se pudo agregar los valores, contacte al adm o vuelva intentarlo!", 4, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.ERROR).setVisible(true);

                    }
                } else {
                    new rojerusan.RSNotifyFade("¡¡Valor Repetido!! ", "Los valore deben ser únicos, intente con otro valor y vuelva intentarlo!", 4, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.INFORMATION).setVisible(true);

                }

            } else if (valor == 1) {//editar
                int id = Integer.valueOf(idTxt.getText());
                int respuesta = new CondicionMigratoria().updateGenero(id, nombre, estado);
                if (respuesta > 0) {
                    new rojerusan.RSNotifyFade("¡¡Actualizado!! ", "Condicion Migratoria actualizada con exito!", 4, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                    limpiarCampos();
                    buscarValorTabla(nombre);
                    ParametrosPanel.actualizarPams("condicion");
                } else {
                    new rojerusan.RSNotifyFade("¡¡ERROR!! ", "Tuvimos problemas para actualizar los valores, contacte al adm o vuelva intentarlo!", 4, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.ERROR).setVisible(true);
                }
            }
        }else{
            new rojerusan.RSNotifyFade("¡¡Campo Vacio!! ", "El campo <Valor> no puede quedar vacio.!", 4, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.INFORMATION).setVisible(true);
        }
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void activoRbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_activoRbStateChanged
      
    }//GEN-LAST:event_activoRbStateChanged

    private void bloqueadoRbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bloqueadoRbStateChanged
       
    }//GEN-LAST:event_bloqueadoRbStateChanged

    private void activoRbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_activoRbItemStateChanged
        estado = "Activo";
    }//GEN-LAST:event_activoRbItemStateChanged

    private void bloqueadoRbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bloqueadoRbItemStateChanged
       estado = "Bloqueado";
    }//GEN-LAST:event_bloqueadoRbItemStateChanged

    private void nombreTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTxtKeyReleased
       if(nombreTxt.getText().length()>43){
           evt.consume();
       }
    }//GEN-LAST:event_nombreTxtKeyReleased

    private void nombreTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTxtKeyPressed
       if(evt.getKeyLocation() == KeyEvent.VK_ESCAPE){
             new Thread(this::reset).start();
       }
    }//GEN-LAST:event_nombreTxtKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSRadioButton activoRb;
    private rojerusan.RSRadioButton bloqueadoRb;
    private javax.swing.ButtonGroup buttonGroup1;
    private rojeru_san.complementos.ButtonPane buttonPane1;
    public RSComponentShade.RSButtonRippleShade editarBtn;
    private RSComponentShade.RSButtonRippleShade guardarBtn;
    private javax.swing.JLabel idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.rsfield.RSTextFullRound nombreTxt;
    public RSComponentShade.RSButtonRippleShade nuevoBtn;
    private RSComponentShade.RSButtonRippleShade resetBtn;
    private rojerusan.RSTableMetro tabla;
    // End of variables declaration//GEN-END:variables

    public void iniciar() {
        llenarGeneros("");
    }

    private void reset() {
        resetBtn.setEnabled(false);
        limpiarCampos();
        resetBtn.setEnabled(true);

    }

    public void llenarGeneros() {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);
        condiciones.clear();
        condiciones = (ArrayList) new CondicionMigratoria().Listar("").clone();
        for (CondicionMigratoria condicion : condiciones) {
            modelo.addRow(new Object[]{
                condicion.getId(), condicion.getNombre(), condicion.getEstado()
            });
        }
        if (condiciones.size() < 1) {
            modelo.addRow(new Object[]{
                "-", "Sin Resultados"
            });
        }
    }
    public void llenarGeneros(String estadox) {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);
        condiciones.clear();
        condiciones = (ArrayList) new CondicionMigratoria().Listar(estadox).clone();
        for (CondicionMigratoria condicion : condiciones) {
            if (condicion.getNombre().contains(estadox)) {
                modelo.addRow(new Object[]{
                condicion.getId(), condicion.getNombre(), condicion.getEstado()
            });
            }
            
        }
        if (condiciones.size() < 1) {
            modelo.addRow(new Object[]{
                "-", "Sin Resultados"
            });
        }
    }

    private void activarDesactivar(boolean llave) {
        nombreTxt.setEditable(llave);
        activoRb.setEnabled(llave);
        bloqueadoRb.setEnabled(llave);
        activoRb.setSelected(true);
    }

    private void limpiarCampos() {
        valor = -1;
        activarDesactivar(false);
        nombreTxt.setText("");
        idTxt.setText("-");
        activoRb.setEnabled(false);
        bloqueadoRb.setEnabled(false);
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);
        nuevoBtn.setEnabled(agregar);
        editarBtn.setEnabled(editar);
        guardarBtn.setEnabled(false);
        resetBtn.setEnabled(true);
        llenarGeneros("");
    }

    private boolean validarCamposLlenos() {
        boolean llave = false;
        if (nombreTxt.getText().length() > 0) {
            llave = true;
        }
        return llave;
    }

    public void buscarValorTabla(String nombrex) {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            if (tabla.getValueAt(i, 1).equals(nombrex)) {
                tabla.changeSelection(i, 1, false, false);
            }
        }
    }

}
