/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

import Clases.Actualizar;
import Clases.tools;
import Ventanas.Index;
import java.awt.Color;
import java.io.File;

/**
 *
 * @author parra
 */
public class panelIndexMenu extends javax.swing.JPanel {

    static String priv = "";
    static panelPacientesTerapeuta pct;
    public static panelNewPaciente pnp;
    static panelVerUsuarios pvu = new panelVerUsuarios();
    static ParametrosPanel pp;
    static panelHome ph = new panelHome();
    static panelMonitoreo pm = new panelMonitoreo();
    public static Index index;
    public panelIndexMenu() {
        initComponents();
        priv = "terapeuta";
        botonear(1);
    }
   

    public panelIndexMenu(String priv,Index index) {
        initComponents();
        this.priv = priv;
        this.index=index;
        /*
        new Thread(new Runnable() {
            @Override
            public void run() {
                
            }
        }).start();
        */
        
        
        pp = new ParametrosPanel();
                pct = new panelPacientesTerapeuta(index);
                 iniciarMenu();
       
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBtns = new javax.swing.ButtonGroup();
        btn1 = new rojeru_san.rsbutton.RSButtonSelectedIcon();
        btn2 = new rojeru_san.rsbutton.RSButtonSelectedIcon();
        btn3 = new rojeru_san.rsbutton.RSButtonSelectedIcon();
        btn4 = new rojeru_san.rsbutton.RSButtonSelectedIcon();
        btn5 = new rojeru_san.rsbutton.RSButtonSelectedIcon();
        btn7 = new rojeru_san.rsbutton.RSButtonSelectedIcon();
        btn8 = new rojeru_san.rsbutton.RSButtonSelectedIcon();
        btn12 = new rojeru_san.rsbutton.RSButtonSelectedIcon();
        btn6 = new rojeru_san.rsbutton.RSButtonRoundRipple();
        rSPanelImage1 = new rojeru_san.rspanel.RSPanelImage();

        setBackground(new java.awt.Color(138, 128, 155));

        btn1.setBackground(new java.awt.Color(138, 128, 155));
        btn1.setForeground(new java.awt.Color(51, 51, 51));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/home_icon.png"))); // NOI18N
        btn1.setText("            Home(OCULTO)");
        grupoBtns.add(btn1);
        btn1.setColorHover(new java.awt.Color(165, 185, 172));
        btn1.setColorLine(new java.awt.Color(51, 51, 51));
        btn1.setEfecto(rojeru_san.rsbutton.RSButtonSelectedIcon.EFECTO.RIPLE);
        btn1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn1.setIconTextGap(10);
        btn1.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(138, 128, 155));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/people_list_filled_icon.png"))); // NOI18N
        btn2.setText("            Mis Pacientes");
        grupoBtns.add(btn2);
        btn2.setColorHover(new java.awt.Color(165, 185, 172));
        btn2.setColorLine(new java.awt.Color(51, 51, 51));
        btn2.setEfecto(rojeru_san.rsbutton.RSButtonSelectedIcon.EFECTO.RIPLE);
        btn2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn2.setIconTextGap(10);
        btn2.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btn2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btn2ItemStateChanged(evt);
            }
        });
        btn2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btn2StateChanged(evt);
            }
        });
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn2MouseExited(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(138, 128, 155));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/people_add_filled_icon.png"))); // NOI18N
        btn3.setText("            Nuevo Paciente");
        grupoBtns.add(btn3);
        btn3.setColorHover(new java.awt.Color(165, 185, 172));
        btn3.setColorLine(new java.awt.Color(51, 51, 51));
        btn3.setEfecto(rojeru_san.rsbutton.RSButtonSelectedIcon.EFECTO.RIPLE);
        btn3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn3.setIconTextGap(10);
        btn3.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btn3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btn3ItemStateChanged(evt);
            }
        });
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn3MouseExited(evt);
            }
        });
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(138, 128, 155));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/user_circle_gear_icon.png"))); // NOI18N
        btn4.setText("            Ver Usuarios");
        grupoBtns.add(btn4);
        btn4.setColorHover(new java.awt.Color(165, 185, 172));
        btn4.setColorLine(new java.awt.Color(51, 51, 51));
        btn4.setEfecto(rojeru_san.rsbutton.RSButtonSelectedIcon.EFECTO.RIPLE);
        btn4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn4.setIconTextGap(10);
        btn4.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btn4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btn4ItemStateChanged(evt);
            }
        });
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn4MouseExited(evt);
            }
        });
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(138, 128, 155));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/increase_chart_data_graph_icon.png"))); // NOI18N
        btn5.setText("            Monitoreo");
        grupoBtns.add(btn5);
        btn5.setColorHover(new java.awt.Color(165, 185, 172));
        btn5.setColorLine(new java.awt.Color(51, 51, 51));
        btn5.setEfecto(rojeru_san.rsbutton.RSButtonSelectedIcon.EFECTO.RIPLE);
        btn5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn5.setIconTextGap(10);
        btn5.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btn5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btn5ItemStateChanged(evt);
            }
        });
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn5MouseExited(evt);
            }
        });
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(138, 128, 155));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/listaEspera.png"))); // NOI18N
        btn7.setText("            Lista de Espera");
        grupoBtns.add(btn7);
        btn7.setColorHover(new java.awt.Color(165, 185, 172));
        btn7.setColorLine(new java.awt.Color(51, 51, 51));
        btn7.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn7.setIconTextGap(10);
        btn7.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(138, 128, 155));
        btn8.setText("            Inicio");
        grupoBtns.add(btn8);
        btn8.setColorHover(new java.awt.Color(165, 185, 172));
        btn8.setColorLine(new java.awt.Color(51, 51, 51));
        btn8.setEfecto(rojeru_san.rsbutton.RSButtonSelectedIcon.EFECTO.RIPLE);
        btn8.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn8.setIconTextGap(10);
        btn8.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn12.setBackground(new java.awt.Color(138, 128, 155));
        btn12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/setting.png"))); // NOI18N
        btn12.setText("            Parámetros");
        grupoBtns.add(btn12);
        btn12.setColorHover(new java.awt.Color(165, 185, 172));
        btn12.setColorLine(new java.awt.Color(51, 51, 51));
        btn12.setEfecto(rojeru_san.rsbutton.RSButtonSelectedIcon.EFECTO.RIPLE);
        btn12.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn12.setIconTextGap(10);
        btn12.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btn12.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btn12ItemStateChanged(evt);
            }
        });
        btn12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn12MouseExited(evt);
            }
        });
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(138, 128, 155));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pdfIconx32px.png"))); // NOI18N
        btn6.setText("  Manual");
        btn6.setColorHover(new java.awt.Color(249, 182, 48));
        btn6.setColorTextHover(new java.awt.Color(51, 51, 51));
        btn6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn6.setIconTextGap(0);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo caps.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSPanelImage1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(rSPanelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        botonear(1);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        botonear(2);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        botonear(3);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        botonear(4);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        botonear(5);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        botonear(7);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        botonear(8);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        botonear(12);
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseEntered
      btn2.setForeground(new Color(51,51,51));
      // btn2.setForeground(new Color(51,51,51));
      //.setFont(new Font("Segoe UI", Font.PLAIN, 15));
    }//GEN-LAST:event_btn2MouseEntered

    private void btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseExited
      //btn2.setForeground(new Color(51,51,51));
      
        if(!btn2.isSelected()){
             btn2.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btn2MouseExited

    private void btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseEntered
       btn3.setForeground(new Color(51,51,51));
       //btn2.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn3MouseEntered

    private void btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseExited
      //btn2.setForeground(new Color(51,51,51));
       
        if(!btn3.isSelected()){
            btn3.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btn3MouseExited

    private void btn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseEntered
       btn4.setForeground(new Color(51,51,51));
       //btn2.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn4MouseEntered

    private void btn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseExited
       //btn2.setForeground(new Color(51,51,51));
        if(!btn4.isSelected()){
            btn4.setForeground(new Color(255,255,255));
        }
       
    }//GEN-LAST:event_btn4MouseExited

    private void btn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseEntered
       btn5.setForeground(new Color(51,51,51));
      // btn2.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn5MouseEntered

    private void btn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseExited
      //btn2.setForeground(new Color(51,51,51));
      if(!btn5.isSelected()){
          btn5.setForeground(new Color(255,255,255));
      } 
      
    }//GEN-LAST:event_btn5MouseExited

    private void btn2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btn2StateChanged
        
//
      
    }//GEN-LAST:event_btn2StateChanged

    private void btn2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btn2ItemStateChanged
        if(btn2.isSelected()){
            btn2.setForeground(new Color(51,51,51));
        }else{
             btn2.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btn2ItemStateChanged

    private void btn3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btn3ItemStateChanged
       if(btn3.isSelected()){
            btn3.setForeground(new Color(51,51,51));
        }else{
             btn3.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btn3ItemStateChanged

    private void btn4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btn4ItemStateChanged
       if(btn4.isSelected()){
            btn4.setForeground(new Color(51,51,51));
        }else{
             btn4.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btn4ItemStateChanged

    private void btn5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btn5ItemStateChanged
      if(btn5.isSelected()){
            btn5.setForeground(new Color(51,51,51));
        }else{
             btn5.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btn5ItemStateChanged

    private void btn12ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btn12ItemStateChanged
      if(btn12.isSelected()){
            btn12.setForeground(new Color(51,51,51));
        }else{
             btn12.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btn12ItemStateChanged

    private void btn12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn12MouseEntered
        btn12.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_btn12MouseEntered

    private void btn12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn12MouseExited
        if(!btn12.isSelected()){
              btn12.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_btn12MouseExited

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        String ruta ="C:\\DataCaps\\Manual-CAPS.docx";
        String urlDescarga = "https://github.com/fParrax/CapsPacientes2022/raw/main/Manual-CAPS.docx";
                              
        File archivo = new File(ruta);
        btn6.setText("Abriendo...");
        btn6.setEnabled(false);
        new Thread(new Runnable() {
            @Override
            public void run() {
               if(!archivo.exists()){
            btn6.setText("Descargando...");       
            new Actualizar().descargar(urlDescarga, "Manual-CAPS.docx");
            new tools().abrirArchivo(ruta);
            btn6.setText("  Manual");
             btn6.setEnabled(true);
        }else{
            new tools().abrirArchivo(ruta);
            btn6.setText("  Manual");
            btn6.setEnabled(true);
        } 

            }
        }).start();
        
        
    }//GEN-LAST:event_btn6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static rojeru_san.rsbutton.RSButtonSelectedIcon btn1;
    public static rojeru_san.rsbutton.RSButtonSelectedIcon btn12;
    public static rojeru_san.rsbutton.RSButtonSelectedIcon btn2;
    public static rojeru_san.rsbutton.RSButtonSelectedIcon btn3;
    public static rojeru_san.rsbutton.RSButtonSelectedIcon btn4;
    public static rojeru_san.rsbutton.RSButtonSelectedIcon btn5;
    private rojeru_san.rsbutton.RSButtonRoundRipple btn6;
    public static rojeru_san.rsbutton.RSButtonSelectedIcon btn7;
    public static rojeru_san.rsbutton.RSButtonSelectedIcon btn8;
    private javax.swing.ButtonGroup grupoBtns;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage1;
    // End of variables declaration//GEN-END:variables

    private static void botonear(int btnx) {
        switch (btnx) {
            case 1:
                btn1.setSelected(true);
                btn2.setSelected(false);
                btn3.setSelected(false);
                btn4.setSelected(false);
                btn5.setSelected(false);
                //btn6.setSelected(false);
                btn7.setSelected(false);
                btn8.setSelected(false);
                btn12.setSelected(false);
                Index.scrollCentral.setViewportView(ph);
                break;

            case 2:
                btn1.setSelected(false);
                btn2.setSelected(true);
                btn3.setSelected(false);
                btn4.setSelected(false);
                btn5.setSelected(false);
                //btn6.setSelected(false);
                btn7.setSelected(false);
                btn8.setSelected(false);
                btn12.setSelected(false);
                    Index.scrollCentral.setViewportView(pct);
                    
                 
                break;

            case 3:
                btn1.setSelected(false);
                btn2.setSelected(false);
                btn3.setSelected(true);
                btn4.setSelected(false);
                btn5.setSelected(false);
                //btn6.setSelected(false);
                btn7.setSelected(false);
                btn8.setSelected(false);
                btn12.setSelected(false);

                Index.scrollCentral.setViewportView(pnp);
                
                
                break;

            case 4:
                btn1.setSelected(false);
                btn2.setSelected(false);
                btn3.setSelected(false);
                btn4.setSelected(true);
                btn5.setSelected(false);
                //btn6.setSelected(false);
                btn7.setSelected(false);
                btn8.setSelected(false);
                btn12.setSelected(false);
                
                Index.scrollCentral.setViewportView(pvu);
                
                
                break;

            case 5:
                btn1.setSelected(false);
                btn2.setSelected(false);
                btn3.setSelected(false);
                btn4.setSelected(false);
                btn5.setSelected(true);
                //btn6.setSelected(false);
                btn7.setSelected(false);
                btn8.setSelected(false);
                btn12.setSelected(false);
                Index.scrollCentral.setViewportView(pm);
                
                
                break;

            

            case 7:
                btn1.setSelected(false);
                btn2.setSelected(false);
                btn3.setSelected(false);
                btn4.setSelected(false);
                btn5.setSelected(false);
                //btn6.setSelected(false);
                btn7.setSelected(true);
                btn8.setSelected(false);
                btn12.setSelected(false);
                
               
                break;

            case 8:
                btn1.setSelected(false);
                btn2.setSelected(false);
                btn3.setSelected(false);
                btn4.setSelected(false);
                btn5.setSelected(false);
                //btn6.setSelected(false);
                btn7.setSelected(false);
                btn8.setSelected(true);
                btn12.setSelected(false);
                
                
                break;

            case 9:
                btn1.setSelected(false);
                btn2.setSelected(false);
                btn3.setSelected(false);
                btn4.setSelected(false);
                btn5.setSelected(false);
                //btn6.setSelected(false);
                btn7.setSelected(false);
                btn8.setSelected(false);
                btn12.setSelected(false);
                
                
                break;

            case 10:
                btn1.setSelected(false);
                btn2.setSelected(false);
                btn3.setSelected(false);
                btn4.setSelected(false);
                btn5.setSelected(false);
                //btn6.setSelected(false);
                btn7.setSelected(false);
                btn8.setSelected(false);
                btn12.setSelected(false);
                
                
                break;

            

            case 12:
                btn1.setSelected(false);
                btn2.setSelected(false);
                btn3.setSelected(false);
                btn4.setSelected(false);
                btn5.setSelected(false);
                //btn6.setSelected(false);
                btn7.setSelected(false);
                btn8.setSelected(false);
                btn12.setSelected(true);
                
                Index.scrollCentral.setViewportView(pp);
                
                break;
        }
    }

    private static void iniciar() {

    }

    private void iniciarMenu() {
        pnp = new panelNewPaciente(index);;
        btn1.setVisible(false);    
        
        btn1.doClick();
        if (priv.equalsIgnoreCase("administrador")) {
            
        }else{
        btn2.setVisible(false);
        btn3.setVisible(false);
        btn4.setVisible(false);
        btn5.setVisible(false);
        btn7.setVisible(false);
        btn8.setVisible(false);
        }
        
        

        if (priv.equalsIgnoreCase("terapeuta") || priv.equalsIgnoreCase("psiquiatra")) {
            btn2.setVisible(true);
            btn12.setVisible(false);
            btn7.setVisible(false);
        }
        
        if (priv.equalsIgnoreCase("trabajador social")) {
            btn3.setVisible(true);
             btn7.setVisible(true);
        }
        
        String privx = priv.toLowerCase();
         if (privx.contains("monitoreo")) {
            btn5.setVisible(true);
        }
        
        
        btn1.setVisible(false);
        
        btn8.setVisible(false);
        
    }
}
