/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

import Ventanas.newPaciente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author parra
 */
public class RnpInfoVulnerabilidad extends javax.swing.JPanel {

    DefaultTableModel modelo;
    boolean llaveInicio = false;
    public RnpInfoVulnerabilidad() {
        initComponents();
        redSoporteTxt.setVisible(false);
        modelo = (DefaultTableModel) tabla.getModel();
        totalSesionesTxt.setVisible(false);
        jLabel7.setVisible(false);
        txtContactoRedSoporte.setVisible(false);
        lbTituloContactoRedsoporte.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        jLabel7 = new javax.swing.JLabel();
        totalSesionesTxt = new RSComponentShade.RSTextFieldShade();
        gpSeguro = new javax.swing.ButtonGroup();
        gpTrabajo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        condicionMigratoriaCombo = new rojerusan.RSComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        discapacidadTxt = new javax.swing.JTextArea();
        redCheck = new rojerusan.RSCheckBox();
        redSoporteTxt = new RSComponentShade.RSTextFieldShade();
        grupoVulnerableCombo = new rojerusan.RSComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla = new rojerusan.RSTableMetro();
        jSeparator1 = new javax.swing.JSeparator();
        txtContactoRedSoporte = new RSComponentShade.RSTextFieldShade();
        lbTituloContactoRedsoporte = new javax.swing.JLabel();
        lbTituloContactoRedsoporte1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtIntegrantesGrupoFamiliar = new RSComponentShade.RSTextFieldShade();
        jLabel6 = new javax.swing.JLabel();
        rbSiSeguro = new rojerusan.RSRadioButton();
        rbNoSeguro = new rojerusan.RSRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtOtroSeguro = new RSComponentShade.RSTextFieldShade();
        rbOtroSeguro = new rojerusan.RSRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtIngresoPeru = new RSComponentShade.RSTextFieldShade();
        jLabel15 = new javax.swing.JLabel();
        rbNoTrabajo = new rojerusan.RSRadioButton();
        rbSiTrabajo = new rojerusan.RSRadioButton();
        txtSiTrabajo = new RSComponentShade.RSTextFieldShade();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        comboNivelEducativo = new rojerusan.RSComboBox();
        txtOtroNivelEducativo = new RSComponentShade.RSTextFieldShade();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtOcupacion = new RSComponentShade.RSTextFieldShade();
        jLabel20 = new javax.swing.JLabel();
        txtSubOcupacion = new RSComponentShade.RSTextFieldShade();

        Eliminar.setText("Eliminar Grupo Vulnerable");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        popUp.add(Eliminar);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total de Sesiones");

        totalSesionesTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalSesionesTxt.setText("0");
        totalSesionesTxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        totalSesionesTxt.setPlaceholder("");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de Vulnerabilidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Condición Migratoria");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿Pertenece a algún grupo Vulnerable?");

        s.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        s.setText("Observaciones de Grupos Vulnerables");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("¿Pertenece a una red de Soporte?");

        condicionMigratoriaCombo.setColorArrow(new java.awt.Color(0, 102, 102));
        condicionMigratoriaCombo.setColorBorde(new java.awt.Color(0, 102, 102));
        condicionMigratoriaCombo.setColorFondo(new java.awt.Color(0, 102, 102));
        condicionMigratoriaCombo.setColorSeleccion(new java.awt.Color(51, 51, 51));
        condicionMigratoriaCombo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N

        discapacidadTxt.setColumns(20);
        discapacidadTxt.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        discapacidadTxt.setLineWrap(true);
        discapacidadTxt.setRows(3);
        jScrollPane1.setViewportView(discapacidadTxt);

        redCheck.setForeground(new java.awt.Color(0, 0, 0));
        redCheck.setText("SI, quiero especificar.");
        redCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                redCheckItemStateChanged(evt);
            }
        });
        redCheck.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                redCheckStateChanged(evt);
            }
        });

        redSoporteTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        redSoporteTxt.setBgShadeHover(new java.awt.Color(0, 0, 0));
        redSoporteTxt.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        redSoporteTxt.setPlaceholder("Especificar(Opcional)");

        grupoVulnerableCombo.setColorArrow(new java.awt.Color(0, 102, 102));
        grupoVulnerableCombo.setColorBorde(new java.awt.Color(0, 102, 102));
        grupoVulnerableCombo.setColorFondo(new java.awt.Color(0, 102, 102));
        grupoVulnerableCombo.setColorSeleccion(new java.awt.Color(51, 51, 51));
        grupoVulnerableCombo.setDisabledIdex("");
        grupoVulnerableCombo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        grupoVulnerableCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                grupoVulnerableComboItemStateChanged(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_add_32px.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grupos Vulnerables", "-"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setBackgoundHead(new java.awt.Color(0, 102, 102));
        tabla.setBackgoundHover(new java.awt.Color(0, 102, 102));
        tabla.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tabla.setColorSecondary(new java.awt.Color(255, 255, 255));
        tabla.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tabla.setComponentPopupMenu(popUp);
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tabla.setShowGrid(true);
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setMinWidth(50);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(50);
            tabla.getColumnModel().getColumn(1).setMaxWidth(50);
        }

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        txtContactoRedSoporte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContactoRedSoporte.setBgShadeHover(new java.awt.Color(0, 0, 0));
        txtContactoRedSoporte.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtContactoRedSoporte.setPlaceholder("Especificar(Opcional)");

        lbTituloContactoRedsoporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTituloContactoRedsoporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloContactoRedsoporte.setText("Contacto de red Soporte");

        lbTituloContactoRedsoporte1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTituloContactoRedsoporte1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloContactoRedsoporte1.setText("(En caso de omitir la Opción \"SI\", se considerará que no pertenece a una red de soporte)");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtIntegrantesGrupoFamiliar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIntegrantesGrupoFamiliar.setBgShadeHover(new java.awt.Color(0, 0, 0));
        txtIntegrantesGrupoFamiliar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtIntegrantesGrupoFamiliar.setPlaceholder("");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("N° de integrantes del grupo familiar ");

        gpSeguro.add(rbSiSeguro);
        rbSiSeguro.setText("Si");
        rbSiSeguro.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        rbSiSeguro.setName("Si"); // NOI18N

        gpSeguro.add(rbNoSeguro);
        rbNoSeguro.setSelected(true);
        rbNoSeguro.setText("No");
        rbNoSeguro.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        rbNoSeguro.setName("No"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tienen SIS-Seguro integral de salud?");

        txtOtroSeguro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOtroSeguro.setBgShadeHover(new java.awt.Color(0, 0, 0));
        txtOtroSeguro.setEnabled(false);
        txtOtroSeguro.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtOtroSeguro.setPlaceholder("");

        gpSeguro.add(rbOtroSeguro);
        rbOtroSeguro.setText("Otro");
        rbOtroSeguro.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        rbOtroSeguro.setName("Otro"); // NOI18N
        rbOtroSeguro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbOtroSeguroItemStateChanged(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Indique Cual (Solo si elije \"otro\")");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtIntegrantesGrupoFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbNoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbSiSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbOtroSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOtroSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIntegrantesGrupoFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOtroSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbOtroSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbSiSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbNoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText(" ¿Cuándo llegó a Perú?");

        txtIngresoPeru.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIngresoPeru.setBgShadeHover(new java.awt.Color(0, 0, 0));
        txtIngresoPeru.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtIngresoPeru.setPlaceholder("Fecha aprox. (Dia/mes/año)");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("¿Actualmente se encuentra laborando?");

        gpTrabajo.add(rbNoTrabajo);
        rbNoTrabajo.setSelected(true);
        rbNoTrabajo.setText("No");
        rbNoTrabajo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N

        gpTrabajo.add(rbSiTrabajo);
        rbSiTrabajo.setText("Si");
        rbSiTrabajo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        rbSiTrabajo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbSiTrabajoItemStateChanged(evt);
            }
        });

        txtSiTrabajo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSiTrabajo.setBgShadeHover(new java.awt.Color(0, 0, 0));
        txtSiTrabajo.setEnabled(false);
        txtSiTrabajo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSiTrabajo.setPlaceholder("");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Indique Cual (Solo si elije \"Si\")");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Nivel educativo.");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("  Describa Cual (Solo Disponible si selecciona \"otro\")");

        comboNivelEducativo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Educación primaria", "d", "d", "d", "d" }));
        comboNivelEducativo.setColorArrow(new java.awt.Color(0, 102, 102));
        comboNivelEducativo.setColorBorde(new java.awt.Color(0, 102, 102));
        comboNivelEducativo.setColorFondo(new java.awt.Color(0, 102, 102));
        comboNivelEducativo.setColorSeleccion(new java.awt.Color(102, 102, 102));
        comboNivelEducativo.setDisabledIdex("");
        comboNivelEducativo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        comboNivelEducativo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboNivelEducativoItemStateChanged(evt);
            }
        });

        txtOtroNivelEducativo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOtroNivelEducativo.setBgShadeHover(new java.awt.Color(0, 0, 0));
        txtOtroNivelEducativo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtOtroNivelEducativo.setPlaceholder("");
        txtOtroNivelEducativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtroNivelEducativoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtIngresoPeru, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rbNoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbSiTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSiTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboNivelEducativo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOtroNivelEducativo, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(2, 2, 2)
                        .addComponent(txtSiTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(2, 2, 2)
                        .addComponent(txtIngresoPeru, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbNoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbSiTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboNivelEducativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOtroNivelEducativo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("   Ocupación");

        txtOcupacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOcupacion.setBgShadeHover(new java.awt.Color(0, 0, 0));
        txtOcupacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtOcupacion.setPlaceholder("");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("   Sub Ocupación");

        txtSubOcupacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubOcupacion.setBgShadeHover(new java.awt.Color(0, 0, 0));
        txtSubOcupacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSubOcupacion.setPlaceholder("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                    .addComponent(txtSubOcupacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(2, 2, 2)
                        .addComponent(txtOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(redCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(redSoporteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtContactoRedSoporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbTituloContactoRedsoporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbTituloContactoRedsoporte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(condicionMigratoriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(48, 48, 48)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(grupoVulnerableCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addComponent(s, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(grupoVulnerableCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(condicionMigratoriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(s)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTituloContactoRedsoporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(redCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTituloContactoRedsoporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(redSoporteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContactoRedSoporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void redCheckStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_redCheckStateChanged
     
    }//GEN-LAST:event_redCheckStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String add = grupoVulnerableCombo.getSelectedItem().toString();
        boolean llave=false;
        
        for(int i=0; i<modelo.getRowCount(); i++){
            if(tabla.getValueAt(i, 0).toString().equals(add)){
                llave=true;
                break;
            }
        }
        if(llave==false){
            modelo.addRow(new Object[]{add});
        }else{
            JOptionPane.showMessageDialog(null, "Valor ya se encuentra registrado para el paciente");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
       int valor = tabla.getSelectedRow();
       if(valor>=0){
           modelo.removeRow(valor);
       }else{
           JOptionPane.showMessageDialog(null, "Debe seleccionar un valor en la tabla para elimianar");
       }
    }//GEN-LAST:event_EliminarActionPerformed

    private void redCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_redCheckItemStateChanged
    redSoporteTxt.setVisible(redCheck.isSelected());
    txtContactoRedSoporte.setVisible(redCheck.isSelected());
    lbTituloContactoRedsoporte.setVisible(redCheck.isSelected());
    
    }//GEN-LAST:event_redCheckItemStateChanged

    private void grupoVulnerableComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_grupoVulnerableComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_grupoVulnerableComboItemStateChanged

    private void rbOtroSeguroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbOtroSeguroItemStateChanged
       if(rbOtroSeguro.isSelected()){
            txtOtroSeguro.setEnabled(rbOtroSeguro.isSelected());
            
       }else{
            txtOtroSeguro.setEnabled(rbOtroSeguro.isSelected());
            txtOtroSeguro.setText("");
       }
       
    }//GEN-LAST:event_rbOtroSeguroItemStateChanged

    private void rbSiTrabajoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbSiTrabajoItemStateChanged
       
        if(rbSiTrabajo.isSelected()){
            txtSiTrabajo.setEnabled(rbSiTrabajo.isSelected());
        }else{
            txtSiTrabajo.setEnabled(rbSiTrabajo.isSelected());
            txtSiTrabajo.setText("");
        }
       
    }//GEN-LAST:event_rbSiTrabajoItemStateChanged

    



    private void comboNivelEducativoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboNivelEducativoItemStateChanged
     /*
        if (newPaciente.a>0) {
            if (comboNivelEducativo.getSelectedItem().toString().equalsIgnoreCase("otro")) {
                txtOtroNivelEducativo.setEnabled(true);
            } else {
                txtOtroNivelEducativo.setEnabled(true);
            }
        }
        */
        
     
    }//GEN-LAST:event_comboNivelEducativoItemStateChanged

    private void txtOtroNivelEducativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtroNivelEducativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtroNivelEducativoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    public rojerusan.RSComboBox comboNivelEducativo;
    public rojerusan.RSComboBox condicionMigratoriaCombo;
    public javax.swing.JTextArea discapacidadTxt;
    public javax.swing.ButtonGroup gpSeguro;
    public javax.swing.ButtonGroup gpTrabajo;
    public rojerusan.RSComboBox grupoVulnerableCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lbTituloContactoRedsoporte;
    public static javax.swing.JLabel lbTituloContactoRedsoporte1;
    private javax.swing.JPopupMenu popUp;
    public rojerusan.RSRadioButton rbNoSeguro;
    public rojerusan.RSRadioButton rbNoTrabajo;
    public rojerusan.RSRadioButton rbOtroSeguro;
    public rojerusan.RSRadioButton rbSiSeguro;
    public rojerusan.RSRadioButton rbSiTrabajo;
    public rojerusan.RSCheckBox redCheck;
    public RSComponentShade.RSTextFieldShade redSoporteTxt;
    private javax.swing.JLabel s;
    public static rojerusan.RSTableMetro tabla;
    public static RSComponentShade.RSTextFieldShade totalSesionesTxt;
    public RSComponentShade.RSTextFieldShade txtContactoRedSoporte;
    public RSComponentShade.RSTextFieldShade txtIngresoPeru;
    public RSComponentShade.RSTextFieldShade txtIntegrantesGrupoFamiliar;
    public RSComponentShade.RSTextFieldShade txtOcupacion;
    public RSComponentShade.RSTextFieldShade txtOtroNivelEducativo;
    public RSComponentShade.RSTextFieldShade txtOtroSeguro;
    public RSComponentShade.RSTextFieldShade txtSiTrabajo;
    public RSComponentShade.RSTextFieldShade txtSubOcupacion;
    // End of variables declaration//GEN-END:variables

public static String validar(){
    String resultado="";
    totalSesionesTxt.setVisible(false);
        jLabel7.setVisible(false);
    return resultado="";
}
public void setLlaveInicio(boolean llave){
    llaveInicio=llave;
}
}
